// Generado por scripts/generar-capas.cjs: huella de cada capa convertida en WebP.
export const CAPAS_GENERADAS: Record<string, string> = {
  "bronce-fondo": "zrnso2cnk",
  "bronce-marco": "1uhwszf6hq",
  "bronce-brillante-fondo": "108aoyb1nw3",
  "bronce-brillante-marco": "1rblwfo6k7",
  "plata-fondo": "di25skxrn",
  "plata-marco": "10uovhi6ix",
  "plata-brillante-fondo": "1px5akh973",
  "plata-brillante-marco": "z213cc6na",
  "oro-fondo": "1gq01m01ow5",
  "oro-marco": "1bsotln653",
  "oro-brillante-fondo": "1k5ezss250e",
  "oro-brillante-marco": "1owy8a1706",
  "elite-fondo": "qkviam25j3",
  "elite-marco": "1c85pr07zt",
  "leyenda-fondo": "td3lc18ud",
  "leyenda-marco": "q75p818hz",
  "if-fondo": "11x1omf6n9",
  "if-marco": "1rkhamb8hz",
  "potm-fondo": "j4pff51qp8",
  "potm-marco": "zf6sm57zt",
  "toty-fondo": "1s1w0f6cls",
  "toty-marco": "op8wjl8ew",
  "mister-debutante-fondo": "ehyg1psw1",
  "mister-debutante-marco": "1eo67md5z1",
  "mister-consolidado-fondo": "12p2owz97f",
  "mister-consolidado-marco": "34pti06dw",
  "mister-elite-fondo": "6xsgrq9y5",
  "mister-elite-marco": "1hj1axm6b3",
  "mister-motm-fondo": "1cxfsiy864",
  "mister-motm-marco": "zf6sm57zt",
  "mister-leyenda-fondo": "dh39xharf",
  "mister-leyenda-marco": "jynmh099w",
  "mister-toty-fondo": "4mg7pem7s",
  "mister-toty-marco": "bsj0fu8hx"
}
